server:
  port: 5055

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5063/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
##Configuracion de la base de datos
spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
  datasource:
    url: jdbc:mariadb://${MARIADB}:3307/nc_user?useSSL=false&serverTimezone=UTC
    username: ${DBADOPETME_USERNAME}
    password: ${DBADOPETME_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  cloud:
    openfeign:
      client:
        config:
          userdetailsapi:
            url: http://localhost:5062/user-details-service/users_details

jwt:
  secret: aEPZLz7azPBLr4G5sfcjBzDtpEExdBZS

admin-paths: #Agregar las urls que quieren que solo el admin acceda, tienen la plantilla comentada de abajo tanto para sin argumentos, como con argumentos en el caso del PUT
  paths: #Si van a usar algun @PathVariable, deben usar "{1}.+". Ej: "/clientes/cliente/{1}.+"
#    -
#      uri: "/clientes/crear"
#      method: "POST"

## Admin Server
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
