server:
  port: 5062

eureka:
  client:
    service-url:
      defaultZone: http://190.223.58.253:5063/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes: #Agregar sus rutas de la forma en la que esta abajo
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: user-details-service
          uri: lb://USER-DETAILS-SERVICE
          predicates:
            - Path=/users_details/**
        # Configuration for pet-service
        - id: pet-service-post
          uri: lb://PET-SERVICE
          predicates:
            - Path=/pet/savewithimage
            - Method=POST
          filters:
            - AuthFilter
        # Configuration for pet-service-get
        - id: pet-service-get
          uri: lb://PET-SERVICE
          predicates:
            - Path=/pet/petuser
            - Method=GET
          filters:
            - AuthFilter
        # Configuration for pet-ID-service-get
        - id: pet-service-get-id
          uri: lb://PET-SERVICE
          predicates:
            - Path=/pet/{id}
            - Method=GET
        # Configuration for pet-ID-service-put
        - id: pet-service-put-id
          uri: lb://PET-SERVICE
          predicates:
            - Path=/pet/{id}
            - Method=PUT
          filters:
            - AuthFilter
        # Configuration for pet-ID-service-delete
        - id: pet-service-delete-id
          uri: lb://PET-SERVICE
          predicates:
            - Path=/pet/{id}
            - Method=DELETE
          filters:
            - AuthFilter
        # Configuration for pet-service-image
        - id: pet-service-delete-id
          uri: lb://PET-SERVICE
          predicates:
            - Path=/pet/petimage
            - Method=GET
        # Configuration for pet-service-image-id
        - id: pet-service-delete-id
          uri: lb://PET-SERVICE
          predicates:
            - Path=/pet/petimages/{id}
            - Method=GET
        # Configuration for pet-service-search
        - id: pet-service-delete-id
          uri: lb://PET-SERVICE
          predicates:
            - Path=/pet/search
            - Method=GET
        # Configuration for species
        - id: specie-service
          uri: lb://SPECIE-SERVICE
          predicates:
            - Path=/species/**
        # Configuration for image
        - id: image-service
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image/**
        # Configuration for breed
        - id: specie-service
          uri: lb://SPECIE-SERVICE
          predicates:
            - Path=/breed/**
        # Configuration for country
        - id: country-service
          uri: lb://COUNTRY-SERVICE
          predicates:
            - Path=/country/**
        # Configuration for state
        - id: state-service
          uri: lb://STATE-SERVICE
          predicates:
            - Path=/state/**
        # Configuration for city
        - id: city-service
          uri: lb://CITY-SERVICE
          predicates:
            - Path=/city/**
public-paths: #Aca deben colocar las rutas que quieren que sean publicas y no necesiten token
  paths:
    # - uri: "/pet/petimage"
    #   method: "GET"
    # - uri: "/pet/petimages/{id}"
    #   method: "GET"
    # - uri: "/pet/search"
    #   method: "GET"

## Admin Server
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
